// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfn7tTzkR_Hewf375mc77TZsiuXVUFHQY',
    appId: '1:999943752611:web:bf6c2464bc7f5a6af22816',
    messagingSenderId: '999943752611',
    projectId: 'waiver-partner-cdc85',
    authDomain: 'waiver-partner-cdc85.firebaseapp.com',
    storageBucket: 'waiver-partner-cdc85.firebasestorage.app',
    measurementId: 'G-PE2WMZ18V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCso01auc8tRp0ATdydKsTcyqybwyolmJ8',
    appId: '1:999943752611:android:beee42f6ccab6a31f22816',
    messagingSenderId: '999943752611',
    projectId: 'waiver-partner-cdc85',
    storageBucket: 'waiver-partner-cdc85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ES_j2YkyXU4HxF27JO7cZS7uP6MQe0I',
    appId: '1:999943752611:ios:f3ebcbc446bd646ef22816',
    messagingSenderId: '999943752611',
    projectId: 'waiver-partner-cdc85',
    storageBucket: 'waiver-partner-cdc85.firebasestorage.app',
    iosBundleId: 'com.waiver.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ES_j2YkyXU4HxF27JO7cZS7uP6MQe0I',
    appId: '1:999943752611:ios:2ef9a91957ccfbbbf22816',
    messagingSenderId: '999943752611',
    projectId: 'waiver-partner-cdc85',
    storageBucket: 'waiver-partner-cdc85.firebasestorage.app',
    iosBundleId: 'com.waiver.driver.waiverDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfn7tTzkR_Hewf375mc77TZsiuXVUFHQY',
    appId: '1:999943752611:web:eea5bba159d11c42f22816',
    messagingSenderId: '999943752611',
    projectId: 'waiver-partner-cdc85',
    authDomain: 'waiver-partner-cdc85.firebaseapp.com',
    storageBucket: 'waiver-partner-cdc85.firebasestorage.app',
    measurementId: 'G-T277CMQBPP',
  );

}