// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWye4BjtlH_mam7O7akbjnVtYFI4SWnI',
    appId: '1:40617336448:web:b5e4bc42cce43e224bd065',
    messagingSenderId: '40617336448',
    projectId: 'waiver-driver-ba8f7',
    authDomain: 'waiver-driver-ba8f7.firebaseapp.com',
    storageBucket: 'waiver-driver-ba8f7.firebasestorage.app',
    measurementId: 'G-7L5JRSG72G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsaBfaoXbsC0Q_AXalVJS0fZPHNqSvTQ',
    appId: '1:40617336448:android:12c516da57489a5e4bd065',
    messagingSenderId: '40617336448',
    projectId: 'waiver-driver-ba8f7',
    storageBucket: 'waiver-driver-ba8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hqlBJmXCsVu546oHqW61edtLvbUlZXs',
    appId: '1:40617336448:ios:41cf96c9d79c715d4bd065',
    messagingSenderId: '40617336448',
    projectId: 'waiver-driver-ba8f7',
    storageBucket: 'waiver-driver-ba8f7.firebasestorage.app',
    iosBundleId: 'com.waiver.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hqlBJmXCsVu546oHqW61edtLvbUlZXs',
    appId: '1:40617336448:ios:5e035436885f91514bd065',
    messagingSenderId: '40617336448',
    projectId: 'waiver-driver-ba8f7',
    storageBucket: 'waiver-driver-ba8f7.firebasestorage.app',
    iosBundleId: 'com.waiver.driver.waiverDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWye4BjtlH_mam7O7akbjnVtYFI4SWnI',
    appId: '1:40617336448:web:235b55ff5b5751a04bd065',
    messagingSenderId: '40617336448',
    projectId: 'waiver-driver-ba8f7',
    authDomain: 'waiver-driver-ba8f7.firebaseapp.com',
    storageBucket: 'waiver-driver-ba8f7.firebasestorage.app',
    measurementId: 'G-FDEQQK632Q',
  );

}